[package]
name = "milo_export"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
pikaxe = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

[lints]
workspace = true